; PlatformIO Project Configuration File
; ESP32-C3 Build Configuration

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

build_unflags = -std=gnu++11
build_flags = 
    -std=gnu++17
    ; Fixes potential core crash issues with legacy code expecting older frameworks
    -DCORE_DEBUG_LEVEL=3

lib_deps = 
    ; para compatibilidad con ESPUI
    https://github.com/mathieucarbou/ESPAsyncWebServer.git
    esphome/AsyncTCP-esphome @ ^2.1.3

    s00500/ESPUI@2.2.1
    adafruit/Adafruit GFX Library@1.10.12
    https://github.com/dmkishi/Dusk2Dawn.git
    https://github.com/markruys/arduino-Max72xxPanel.git
    https://github.com/PaulStoffregen/Time.git
    mathertel/RotaryEncoder@1.5.3

; Enforce strict library tracking dependency management
lib_compat_mode = strict

# Le indicamos a PlatformIO que ignore la librería duplicada y la externa de LittleFS
lib_ignore = 
    LittleFS_esp32
    ESP Async WebServer